version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./prod_config/nginx:/etc/nginx/conf.d:rw
      - ./prod_config/logs:/var/log/nginx:rw
  app:
    build: .
    container_name: app
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app
