"""empty message

Revision ID: 154c2785128e
Revises: 9da07316fe8a
Create Date: 2020-09-12 02:47:49.704493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154c2785128e'
down_revision = '9da07316fe8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
