"""empty message

Revision ID: 5eda126817f9
Revises: 
Create Date: 2020-09-27 07:34:50.449426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eda126817f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_address_user_id_fkey', 'user_address', type_='foreignkey')
    op.create_foreign_key(None, 'user_address', 'users', ['user_id'], ['id'])
    op.drop_constraint('user_role_user_id_fkey', 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_public_id_key', 'users', type_='unique')
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_public_id_key', 'users', ['public_id'])
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key('user_role_user_id_fkey', 'user_role', 'users', ['user_id'], ['public_id'])
    op.drop_constraint(None, 'user_address', type_='foreignkey')
    op.create_foreign_key('user_address_user_id_fkey', 'user_address', 'users', ['user_id'], ['public_id'])
    # ### end Alembic commands ###
