"""empty message

Revision ID: 9da07316fe8a
Revises: 
Create Date: 2020-09-12 01:40:16.554145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da07316fe8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
